// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
      // TODO: Handle this case.
      case TargetPlatform.linux:
      // TODO: Handle this case.
      case TargetPlatform.windows:
        return web;
      // TODO: Handle this case.
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiw9vPwuWHlSXnw2cEo3WcRbpY9TpR65A',
    appId: '1:827584649778:android:3c835a1585e76d90b33a2b',
    messagingSenderId: '827584649778',
    projectId: 'neeknots-604ce',
    storageBucket: 'neeknots-604ce.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    iosBundleId: 'com.redefine.neeknots',
    apiKey: 'AIzaSyDZn7swz4m5ooEQDdYAjVkq4IqnsVZF1bY',
    appId: '1:827584649778:ios:86b108c3370455b5b33a2b',
    messagingSenderId: '827584649778',
    projectId: 'neeknots-604ce',
    storageBucket: 'neeknots-604ce.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAA3Ka_9Jhnncf7mTly2AnJC8VT95MIz_8",
      authDomain: "yoga-buddy-266417.firebaseapp.com",
      databaseURL: "https://yoga-buddy-266417.firebaseio.com",
      projectId: "yoga-buddy-266417",
      storageBucket: "yoga-buddy-266417.appspot.com",
      messagingSenderId: "380744735472",
      appId: "1:380744735472:web:d16f75db3520f6b6234035",
      measurementId: "G-1J6ZPSTCE5");
}
