// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
      // TODO: Handle this case.
      case TargetPlatform.linux:
      // TODO: Handle this case.
      case TargetPlatform.windows:
        return web;
      // TODO: Handle this case.
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuiduBnXasIFR_vb4G3bU4Nm96A9tQIaQ',
    appId: '1:1027672009884:android:519b3c6e8f4fbce73a9159',
    messagingSenderId: '1027672009884',
    projectId: 'neeknots-a8758',
    storageBucket: 'neeknots-a8758.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    iosBundleId: 'com.redefine.neeknots',
    apiKey: 'AIzaSyDZn7swz4m5ooEQDdYAjVkq4IqnsVZF1bY',
    appId: '1:827584649778:ios:86b108c3370455b5b33a2b',
    messagingSenderId: '827584649778',
    projectId: 'neeknots-604ce',
    storageBucket: 'neeknots-604ce.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCOdqy5v0vZpfP59275K6RqCaszeKYhz-0",
      authDomain: "neeknots-a8758.firebaseapp.com",
      databaseURL: "https://neeknots-a8758-default-rtdb.firebaseio.com",
      projectId: "neeknots-a8758",
      storageBucket: "neeknots-a8758.firebasestorage.app",
      messagingSenderId: "1027672009884",
      appId: "1:1027672009884:web:caf81d5b167a2bbf3a9159",
      measurementId: "G-M3HZWXWJRL");
}
