name: Flutter Web Build & Deploy

on:
  push:
    branches:
      - main  # deploy whenever you push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout the repository
    - uses: actions/checkout@v3

    # 2️⃣ Install Flutter
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.1' # change to your Flutter version

    # 3️⃣ Get Flutter dependencies
    - run: flutter pub get

    # 4️⃣ Build Flutter web
    - run: flutter build web --release

    # 5️⃣ Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
